spring.application.name=ai-demo
server.port=8080

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

oci.genai.auth-mode=config_file
oci.genai.chat-format=cohere
oci.genai.profile=DEFAULT
oci.genai.temperature=0.3
oci.genai.top-p=0.75
oci.genai.max-tokens=600
oci.genai.history-limit=8
